### ISSUE TITLE
Schematic diagram?

### ISSUE THREAD

**Issue by secp8x32** [JCGobbi/DC-AC_Inverter-STM32F429#1]
Please upload schematic diagram if available

**Comment by JCGobbi** [comment]
This is only a software project, there is no intention to publish schematics here.
I have used the Open Source Motor Control (OSMC) H-bridge from http://www.robotpower.com/products/osmc_info.html. You may download the schematics there.

**Comment by secp8x32** [comment]
okay, thank you.
